### ISSUE TITLE
Fix IDA search

### ISSUE THREAD

**Issue by matthiasblum** [ProteinsWebTeam/interpro7-client#520] opened 2023-10-04 12:45 UTC
A few issues spotted:

- Seems to fail if the Pfam or InterPro entry search doesn't return any result
- Options (entries returned after a search) are shared between domains. This is counter-intuitive since each domain has its own search input.
- Entry searched are not enqueued and there is no timer between searches so if start typing `ATPase`, the following searches are executed:
  - `A`
  - `AT`
  - `ATP`
  - etc.
- Options are the union of all search results, not of the latest only

**Comment by gustavo-salazar** [comment] 2024-01-04 16:51
working on this while #557 is been reviewed.

---------

> * Seems to fail if the Pfam or InterPro entry search doesn't return any result

Not able to replicate, I put a word that doesn't bring any results and just says not options.

> * Options (entries returned after a search) are shared between domains. This is counter-intuitive since each domain has its own search input.

Mhh, my idea here is that we have a set of options where to match from. the results of one `<select>` can be used in other ones because they will get filtered by the text in the field. Or am I missing something?

> * Entry searched are not enqueued and there is no timer between searches so if start typing `ATPase`, the following searches are executed:
>   
>   * `A`
>   * `AT`
>   * `ATP`
>   * etc.

Good point, I'm adding a `debounce` in here to avoid that.

> * Options are the union of all search results, not of the latest only

How is this different from your second point?

**Comment by matthiasblum** [comment] 2024-01-04 18:35
> 
> > * Seems to fail if the Pfam or InterPro entry search doesn't return any result
> 
> Not able to replicate, I put a word that doesn't bring any results and just says not options.
> 

I still can reproduce on the live website, but not on the `ts-ida-search` branch, so I guess it's fixed. :grin: 

> > * Options (entries returned after a search) are shared between domains. This is counter-intuitive since each domain has its own search input.
> 
> Mhh, my idea here is that we have a set of options where to match from. the results of one `<select>` can be used in other ones because they will get filtered by the text in the field. Or am I missing something?
> 

1. Add a domain to include. Paste _PF00051_. Only one suggestion: `PF00051`. Select it.
2. Add a second domain to include. Paste _PF0000_. Nine suggestions (`PF00001` to `PF00009`). Select `PF00002`.
3. If you expand the dropdown of the first domain, the suggestions of the second domain are there.

It's not a huge deal, since as you pointed searching again for _PF00051_ in the first domain will return `PF00051` only. But I find a bit odd that the content of a dropdown may change because a search was performed in another field.

> 
> > * Options are the union of all search results, not of the latest only
> 
> How is this different from your second point?

What I _think_ I meant, it's that suggestions are piling up:

1. Search for _PF00001_, and select `PF00001`: domain architectures involving `PF00001` are displayed.
2. In the same domain, search for _PF00002_, and select `PF00002`: now domain architectures involving `PF00002` are displayed.
3. If you expand the dropdown of the domain, both `PF00001` and `PF00002` are there.

Since the latest search yielded `PF00002` only, I would expect the options to include `PF00002` only.

**Comment by gustavo-salazar** [comment] 2024-02-27 11:50
I'm tempted to close this issue. The way I see it, the fact that the selects share the list of suggestions is a feature, not a bug

**Closed** 2024-03-25 14:26 UTC
Labels: bug
